"""
Band-level calibration table for the traction interface (supplementary).

Compares, on the full filtered telemetry, each weather band's empirical mean
intensity against (i) the leave-Route-52-out interface's mean prediction over
the same runs and (ii) the interface evaluated at the Route 52 operating
speed, i.e. the value the planning instance actually uses. The last column is
the shift a pooled band-mean substitute would cause. Requires the raw
telemetry (heating_system_study repo); the emitted .tex archives only the
aggregated statistics.

Usage: python3 make_bandcal_table.py
"""

import os

import numpy as np
import pandas as pd

REPO = "/Users/natomanzolli/Documents/GitHub/heating_system_study"
V52 = 19.5  # Route 52 branch mean speed (branches span 19.0-19.9 km/h)
BANDS = [("Mild", 0, 5, 2.5), ("Cold", -5, 0, -2.5),
         ("Very cold", -10, -5, -7.5), ("Extreme", -15, -10, -12.5),
         ("Severe", -99, -15, -17.5)]

df = pd.read_excel(f"{REPO}/data/TTC_Preprocessed_version2_2.xlsx")
d = df[(df["Distance [km]"] > 3) & (df["DT Energy Used [kWh]"] > 0)
       & df["Avg Ambient Temp [degC]"].notna()
       & (df["Vehicle Speed [km/h]"] > 5)].copy()
d["ekm"] = d["DT Energy Used [kWh]"] / d["Distance [km]"]
d = d[(d["ekm"] > 0.3) & (d["ekm"] < 4)]
d["route"] = d["Route  Number"].astype(str).str.strip().str.replace(
    r"\.0$", "", regex=True)

loo = d[d["route"] != "52"]
X = np.column_stack([np.ones(len(loo)),
                     np.maximum(0, 5 - loo["Avg Ambient Temp [degC]"]),
                     loo["Vehicle Speed [km/h]"]])
c, *_ = np.linalg.lstsq(X, loo["ekm"], rcond=None)


def reg(T, v):
    return c[0] + c[1] * np.maximum(0, 5 - T) + c[2] * v


T, v = d["Avg Ambient Temp [degC]"], d["Vehicle Speed [km/h]"]
rows, ns, ybars, yhats = [], [], [], []
for nm, lo, hi, rep in BANDS:
    s = d[(T >= lo) & (T < hi)]
    n, n52 = len(s), int((s["route"] == "52").sum())
    emp, sd = s["ekm"].mean(), s["ekm"].std()
    regmean = reg(s["Avg Ambient Temp [degC]"],
                  s["Vehicle Speed [km/h]"]).mean()
    r52val = float(reg(rep, V52))
    ns.append(n); ybars.append(emp); yhats.append(regmean)
    rng = (r"$<{-15}$" if lo < -20 else f"$[{lo},{hi})$")
    rows.append(
        f"{nm} & {rng} & {n:,} & {n52} & "
        f"{emp:.3f} $\\pm$ {sd:.3f} & {regmean:.3f} & "
        f"{100*(regmean-emp)/emp:+.1f} & {r52val:.3f} & "
        f"{100*(emp-r52val)/r52val:+.1f} \\\\")

# band-level agreement: mean absolute and maximum relative error of the
# interface's within-band mean prediction against the empirical band mean.
# (An R^2 across five band means is dominated by the two large, nearly equal
# mild/cold bands and is not a meaningful statistic here.)
ns, ybars, yhats = map(np.array, (ns, ybars, yhats))
relerr = np.abs(yhats - ybars) / ybars * 100
mae_band, max_band = relerr.mean(), relerr.max()

body = r"""\begin{table}[!ht]
\caption{Band-level calibration of the traction interface on the full
filtered telemetry. ``Interface (band)'' is the leave-Route-52-out fit
averaged over the same runs; ``interface (R52)'' is its value at the band
temperature and the Route~52 operating speed, i.e.\ the planning input.
``Swap'' is the shift a pooled band-mean substitute would cause. Mean
absolute band-level error %.1f\%%; maximum %.1f\%%.}
\label{tab:supp-bandcal}
\centering
\footnotesize
\setlength{\tabcolsep}{5pt}
\renewcommand{\arraystretch}{1.12}
\begin{tabular}{@{}llrrccccc@{}}
\toprule
\textbf{Band} & \textbf{$T$ ($^\circ$C)} & \textbf{$n$} &
\textbf{$n_{52}$} & \textbf{\makecell{Empirical\\(kWh/km)}} &
\textbf{\makecell{Interface\\(band)}} & \textbf{\makecell{Gap\\(\%%)}} &
\textbf{\makecell{Interface\\(R52)}} & \textbf{\makecell{Swap\\(\%%)}} \\
\midrule
%s
\bottomrule
\end{tabular}
\end{table}
""" % (mae_band, max_band, "\n".join(rows))
stamp = ("% GENERATED by make_bandcal_table.py from the telemetry pipeline.\n"
         "% Do not edit by hand - regenerate instead.\n")
os.makedirs("supp_tables", exist_ok=True)
for dst in ("supp_tables", "../Overleaf/supp_tables",
            "../Overleaf/short/supp_tables"):
    if os.path.isdir(dst):
        open(os.path.join(dst, "tab_bandcal.tex"), "w").write(stamp + body)
print(f"band MAE={mae_band:.1f}%  max={max_band:.1f}%")
print("wrote tab_bandcal.tex")
