"""
Generate the supplementary-material tables from the v6 result files.

Same rule as the main tables: nothing is transcribed. Emits into
supp_tables/ and mirrors into ../Overleaf/supp_tables/.

  tab_sens.tex        every sensitivity run, with its gap
  tab_reliability.tex out-of-sample service by band, design and stress level
  tab_routes.tex      per-route detail of the fragmented division case
  tab_runs.tex        full run inventory (label, bounds, gap, host, runtime)

Usage: ROUTE_INPUTS=route52_inputs_v5.json python3 make_supp_tables.py
"""

import json
import os
import re

os.environ.setdefault("ROUTE_INPUTS", "route52_inputs_v5.json")
import route52_prototype as R

OUT = "supp_tables"
# both manuscript trees, so the submission master never holds a stale copy
# submission master only; the long draft at ../Overleaf is a frozen archive
TEXDIRS = [d for d in (os.path.join("..", "Overleaf", "short", "supp_tables"),)
           if os.path.isdir(os.path.dirname(d))]
os.makedirs(OUT, exist_ok=True)

BAND = {"mild": "Mild", "cold": "Cold", "verycold": "Very cold",
        "extreme": "Extreme", "severe": "Severe"}
W = {"mild": 45, "cold": 45, "verycold": 36, "extreme": 19, "severe": 6}


def load(fn):
    return json.load(open(fn)) if os.path.exists(fn) else None


def write(name, body):
    stamp = ("% GENERATED by make_supp_tables.py -- do not edit by hand.\n")
    for d in [OUT] + TEXDIRS:
        os.makedirs(d, exist_ok=True)
        open(os.path.join(d, name), "w").write(stamp + body)
    print("wrote", name)


def esc(s):
    return s.replace("_", r"\_")


# ------------------------------------------------------------ sensitivities
def table_sens(runs):
    base = runs.get("policy_lam100")
    pat = re.compile(r"^(ffh_om_|ffh_capex_|grid_|batt_|derate_|reserve_|"
                     r"spare_|precond_tau_|frozen_z|n_minus_1)")
    sel = sorted(l for l in runs if pat.match(l))
    if not sel or not base:
        print("SKIP tab_sens")
        return
    rows = []
    for l in sel:
        r = runs[l]
        d = (r["F1"] - base["F1"]) / 1e3
        fleet = ", ".join(f"{v}$\\times$" + k.replace("NF-", "")
                          for k, v in sorted(r["fleet"].items()))
        rows.append(f"{esc(l)} & {r['F1']/1e3:,.1f} & {d:+.1f} & "
                    f"{r['abs_gap']:,.0f} & {r['co2_t']:.2f} & "
                    f"{r['diesel_L']:,.0f} & {fleet} \\\\")
    body = r"""\begin{table}[!ht]
\caption{Route~52 sensitivity runs, with $\Delta F_1$ relative to the
$\lambda=100$~CAD/t\COtwo{} solution.}
\label{tab:supp-sens}
\centering
\footnotesize
\setlength{\tabcolsep}{4pt}
\begin{tabular}{@{}lrrrrrl@{}}
\toprule
\textbf{Run} & \textbf{$F_1$ (kCAD/yr)} & \textbf{$\Delta F_1$} &
\textbf{Gap (CAD)} & \textbf{\COtwo{} (t/yr)} & \textbf{Diesel (L)} &
\textbf{Fleet} \\
\midrule
%s
\bottomrule
\end{tabular}
\end{table}
""" % "\n".join(rows)
    write("tab_sens.tex", body)


# ---------------------------------------------------------------- reliability
def table_reliability():
    a = load(os.environ.get("SUPP_REL_BASE", "reliability_reserve10.json"))
    z = load(os.environ.get("SUPP_REL_ZERO", "reliability_zeroemission.json"))
    full = load(os.environ.get("SUPP_REL_FULL", "reliability_v5_full3levels.json"))
    if not (a and z):
        print("SKIP tab_reliability")
        return
    rows = []
    for w in W:
        A = a["levels"]["heat_cv_0.00"][w]
        Z = z["levels"]["heat_cv_0.00"][w]
        rows.append(
            f"{BAND[w]} & {A['T']:.1f} & {W[w]} & "
            f"{100*A['p_soc_floor_ok']:.1f} & {100*A['p_all_trips_served']:.1f} & "
            f"{A['expected_shortfall_kWh']:.2f} & "
            f"{100*Z['p_soc_floor_ok']:.1f} & {100*Z['p_all_trips_served']:.1f} & "
            f"{Z['expected_shortfall_kWh']:.2f} \\\\")
    fa = sum(a["levels"]["heat_cv_0.00"][w]["p_soc_floor_ok"] * W[w]
             for w in W) / 151
    fz = sum(z["levels"]["heat_cv_0.00"][w]["p_soc_floor_ok"] * W[w]
             for w in W) / 151
    sa = sum(a["levels"]["heat_cv_0.00"][w]["p_all_trips_served"] * W[w]
             for w in W) / 151
    sz = sum(z["levels"]["heat_cv_0.00"][w]["p_all_trips_served"] * W[w]
             for w in W) / 151
    ea = sum(a["levels"]["heat_cv_0.00"][w]["expected_shortfall_kWh"] * W[w]
             for w in W)
    ez = sum(z["levels"]["heat_cv_0.00"][w]["expected_shortfall_kWh"] * W[w]
             for w in W)
    rows.append(r"\midrule \textbf{Winter-weighted} & & 151 & "
                f"{100*fa:.2f} & {100*sa:.2f} & {ea:.1f} & "
                f"{100*fz:.2f} & {100*sz:.2f} & {ez:.1f} \\\\")
    body = r"""\begin{table}[!ht]
\caption{Out-of-sample service by weather band under empirical
block-correlated traction uncertainty.}
\label{tab:supp-rel}
\centering
\footnotesize
\setlength{\tabcolsep}{3.4pt}
\begin{tabular}{@{}lrrrrrrrr@{}}
\toprule
& & & \multicolumn{3}{c}{\textbf{Economic baseline}} &
\multicolumn{3}{c}{\textbf{Full electrification}} \\
\cmidrule(lr){4-6}\cmidrule(lr){7-9}
\textbf{Band} & \textbf{$T$} & \textbf{d/yr} &
\textbf{Floor \%%} & \textbf{Reserve \%%} & \textbf{kWh} &
\textbf{Floor \%%} & \textbf{Reserve \%%} & \textbf{kWh} \\
\midrule
%s
\bottomrule
\end{tabular}
\end{table}
""" % "\n".join(rows)
    write("tab_reliability.tex", body)

    if full:
        lv = full["levels"]
        rws = []
        for key in sorted(lv):
            cv = key.replace("heat_cv_", "")
            ww = lv[key]["winter_weighted"]
            per = " & ".join(f"{100*lv[key][w]['p_all_trips_served']:.1f}"
                             for w in W)
            rws.append(f"{cv} & {per} & {100*ww['p_day_fully_served']:.1f} & "
                       f"{ww['expected_shortfall_kWh_per_winter']:,.1f} \\\\")
        body2 = r"""\begin{table}[!ht]
\caption{Cabin-heat stress levels: share of reserve-compliant days
by band on the economic baseline design.}
\label{tab:supp-stress}
\centering
\footnotesize
\begin{tabular}{@{}lrrrrrrr@{}}
\toprule
\textbf{CV} & \textbf{Mild} & \textbf{Cold} & \textbf{V.\ cold} &
\textbf{Extreme} & \textbf{Severe} & \textbf{Winter \%%} &
\textbf{kWh/winter} \\
\midrule
%s
\bottomrule
\end{tabular}
\end{table}
""" % "\n".join(rws)
        write("tab_stress.tex", body2)


# ------------------------------------------------------------- division routes
def table_routes(div):
    A = (div or {}).get("cases", {}).get("A_fragmented", {})
    per = A.get("per_route")
    if not per:
        print("SKIP tab_routes")
        return
    rows = []
    for r in sorted(per, key=lambda k: -per[k]["n_buses"]):
        v = per[r]
        rows.append(f"{r} & {v['n_buses']} & {v['n_ffh']} & "
                    f"{100*v['n_ffh']/max(1,v['n_buses']):.0f} & "
                    f"{v['differentiating_cost']/1e3:,.1f} & "
                    f"{v['abs_gap']:,.0f} \\\\")
    tot = sum(v["abs_gap"] for v in per.values())
    rows.append(r"\midrule Total & %d & %d & %.0f & %.1f & %s \\" % (
        A["n_buses"], A["n_ffh"], 100*A["n_ffh"]/A["n_buses"],
        A["differentiating_cost"]/1e3, f"{tot:,.0f}"))
    body = r"""\begin{table}[!ht]
\caption{Fragmented division case: independent per-route solutions.}
\label{tab:supp-routes}
\centering
\footnotesize
\begin{tabular}{@{}lrrrrr@{}}
\toprule
\textbf{Route} & \textbf{Blocks} & \textbf{FFH} & \textbf{FFH \%%} &
\textbf{Diff.\ cost (kCAD)} & \textbf{Gap (CAD)} \\
\midrule
%s
\bottomrule
\end{tabular}
\end{table}
""" % "\n".join(rows)
    write("tab_routes.tex", body)


# ------------------------------------------------------------- run inventory
def table_runs(runs, prov):
    pr = (prov or {}).get("runs", {})
    rows = []
    for l in sorted(runs):
        r = runs[l]
        host = r.get("host", "---")
        host = "laptop" if "MacBook" in host else ("server" if "manager" in host
                                                   else host)
        lam = r.get("lam", 0.0)
        carbon = r["cost_parts"].get("carbon_cost", 0.0)
        rows.append(f"{esc(l)} & {r['F1']/1e3:,.1f} & {r['co2_t']:.2f} & "
                    f"{carbon/1e3:.1f} & {r['obj']/1e3:,.1f} & "
                    f"{r['lb']/1e3:,.1f} & {r['abs_gap']:,.0f} & "
                    f"{r['time_s']:,.0f} & {r['status']} & {host} \\\\")
    body = r"""\begin{table}[!ht]
\caption{Complete Route~52 run inventory. $F_1$ is resource cost excluding
carbon payments; the solver objective is $F_1+\lambda F_2$ for carbon-price
runs and $F_1$ otherwise, so the two columns differ only where $\lambda>0$.
Costs in kCAD/yr, gap in CAD/yr. Gurobi status: 2 optimal within the declared
absolute tolerance, 9 time limit, 17 soft memory limit (a valid incumbent and
bound were returned in every case).}
\label{tab:supp-runs}
\centering
\scriptsize
\setlength{\tabcolsep}{4pt}
\begin{tabular}{@{}lrrrrrrrrl@{}}
\toprule
\textbf{Run} & \textbf{$F_1$} & \textbf{$F_2$ (t)} & \textbf{$\lambda F_2$} &
\textbf{Objective} & \textbf{Bound} & \textbf{Gap} &
\textbf{Time (s)} & \textbf{St.} & \textbf{Host} \\
\midrule
%s
\bottomrule
\end{tabular}
\end{table}
""" % "\n".join(rows)
    write("tab_runs.tex", body)


if __name__ == "__main__":
    d = load(os.environ.get("TAB_RES", "campaign_v5_results.json"))
    runs = {r["label"]: r for r in d["runs"]
            if "error" not in r and not r.get("infeasible")}
    div = load(os.environ.get("TAB_DIV", "campaign_division_v5.json"))
    prov = load(os.environ.get("TAB_PROV", "provenance_v5.json"))
    table_sens(runs)
    table_reliability()
    table_routes(div)
    table_runs(runs, prov)
