"""
Generate every manuscript table from the v6 result files (protocol Section 6,
item 'Generate all final manuscript tables programmatically from model
outputs. Avoid manual transcription.').

Emits LaTeX fragments into tables_v6/ :

  tab_scen.tex      scenario operation of the carbon-price design (Table IV)
  tab_designs.tex   frontier designs and certified bounds       (Table V)
  tab_division.tex  fragmented vs coordinated division cases
  tab_stability.tex near-optimal equipment ranges
  tab_comp.tex      computational performance

Every number is read from campaign_v5_results.json / campaign_division_v5.json
/ provenance_v5.json. Nothing is typed in.

Table IV's cost column is split rather than left as the ambiguous "Energy
cost" of earlier drafts: electricity and diesel are reported separately and
their sum is labelled total variable energy cost. Capital, demand charges and
FFH O&M are NOT in it -- those are annual, not per representative day, and
folding them in was what made the old column unreadable.

Usage: ROUTE_INPUTS=route52_inputs_v5.json python3 make_tables_v6.py
"""

import json
import os

os.environ.setdefault("ROUTE_INPUTS", "route52_inputs_v5.json")
import route52_prototype as R

# Written to the code tree (archive) and straight into the manuscript tree,
# so main.tex picks the tables up with \input and no file is ever copied by
# hand -- that hand copy is exactly where stale numbers used to creep in.
OUTDIR = "tables_v6"
os.makedirs(OUTDIR, exist_ok=True)
# both manuscript trees: long draft (../Overleaf) and submission master
# (../Overleaf/short) each \input their own tables_v6/
# submission master only; the long draft at ../Overleaf is a frozen archive
TEXDIRS = []
for base in (os.path.join("..", "Overleaf", "short"),):
    if os.path.isdir(base):
        d = os.path.join(base, "tables_v6")
        os.makedirs(d, exist_ok=True)
        TEXDIRS.append(d)
RES = os.environ.get("TAB_RES", "campaign_v5_results.json")
DIV = os.environ.get("TAB_DIV", "campaign_division_v5.json")
PROV = os.environ.get("TAB_PROV", "provenance_v5.json")

BAND_LABEL = {"mild": "Mild", "cold": "Cold", "verycold": "Very cold",
              "extreme": "Extreme", "severe": "Severe",
              "offseason": "Off-season"}


def load(fn):
    return json.load(open(fn)) if os.path.exists(fn) else None


def num(x, d=0):
    """Thousands-separated fixed-decimal, or an em dash for missing data."""
    if x is None:
        return "---"
    return f"{x:,.{d}f}"


def write(name, body):
    stamp = ("% GENERATED by make_tables_v6.py from campaign result files.\n"
             "% Do not edit by hand - regenerate instead.\n")
    for d in [OUTDIR] + TEXDIRS:
        open(os.path.join(d, name), "w").write(stamp + body)
    print("wrote", name)


# ---------------------------------------------------------------- Table IV
# per-scenario operating record of the ECONOMIC BASELINE, so the supplement
# table and the manuscript's weather-adaptive-operation figure describe the
# same run (advisor consistency requirement)
def table_scen(runs, label="econ_lam0"):
    r = runs.get(label)
    if not r or "scen_ops" not in r:
        print(f"SKIP tab_scen: {label} has no scen_ops "
              f"(record predates the campaign_v5.py change); re-solve it or "
              f"pick a label that has it")
        return
    rows = []
    for w in R.SCEN:
        s = r["scen_ops"][w]
        tot = s["q_el_kWh"] + s["q_ffh_kWh"]
        share = 100.0 * s["q_ffh_kWh"] / tot if tot > 1e-9 else 0.0
        dsl_cost = R.DIESEL_PRICE * s["diesel_L"]
        rows.append(
            f"{BAND_LABEL.get(w, w):<10} & {s['T']:>6.1f} & {s['days']:>3d} & "
            f"{num(s['q_el_kWh'])} & {num(s['q_ffh_kWh'])} & {share:.0f} & "
            f"{num(s['diesel_L'])} & {num(s['precond_kWh'])} & "
            f"{num(s['electricity_cost'])} & {num(dsl_cost)} & "
            f"{num(s['electricity_cost'] + dsl_cost)} \\\\")
    body = r"""\begin{table*}[!t]
\caption{Scenario operation of the economic baseline design, per
representative day.}
\label{tab:scen}
\centering
\footnotesize
\setlength{\tabcolsep}{4pt}
\renewcommand{\arraystretch}{1.12}
\begin{tabular}{@{}lrrrrrrrrrr@{}}
\toprule
\textbf{Band} &
\textbf{$T_\omega$ ($^\circ$C)} &
\textbf{\makecell{Weight\\(d/yr)}} &
\textbf{\makecell{Electric heat\\(kWh/d)}} &
\textbf{\makecell{FFH heat\\(kWh/d)}} &
\textbf{\makecell{FFH share\\(\%%)}} &
\textbf{\makecell{Diesel\\(L/d)}} &
\textbf{\makecell{Precond.\\(kWh/d)}} &
\textbf{\makecell{Electricity\\(CAD/d)}} &
\textbf{\makecell{Diesel cost\\(CAD/d)}} &
\textbf{\makecell{Total variable\\energy (CAD/d)}} \\
\midrule
%s
\bottomrule
\end{tabular}
\end{table*}
""" % ("\n".join(rows),)
    write("tab_scen.tex", body)


# ----------------------------------------------------------------- Table V
def table_designs(runs, labels=None):
    """Consolidated Route-52 experiment table: the designs that explain the
    frontier's transitions plus the deterministic and N-1 benchmarks, with
    out-of-sample reliability where it was evaluated (E8)."""
    default = os.environ.get(
        "TAB_DESIGNS", "econ_lam0,eps_0.50,eps_0.20,eps_0.00,det_meanT")
    labels = labels or [l for l in default.split(",") if l in runs]
    sel = [runs[l] for l in labels]
    if not sel:
        print("SKIP tab_designs: no frontier runs")
        return

    def cnt(r, pred):
        return sum(v for k, v in r["fleet"].items()
                   if pred(next(bc for bc in R.BUS_CLASSES if bc.name == k)))

    def fleet_of(r, at_depot):
        parts = []
        for key, v in sorted(r["chargers"].items()):
            n, p = key.split(":")
            if (n == "depot") is at_depot:
                parts.append(rf"{v}$\times${p}")
        return ", ".join(parts) if parts else "---"

    # out-of-sample floor compliance exists only for the designs the E8
    # harness evaluated: the lambda=100 design (composition identical to the
    # baseline) and the zero-emission endpoint
    rel = {}
    ra = load(os.environ.get("TAB_REL_BASE", "reliability_reserve10.json"))
    rz = load(os.environ.get("TAB_REL_ZERO", "reliability_zeroemission.json"))
    W = {"mild": 45, "cold": 45, "verycold": 36, "extreme": 19, "severe": 6}
    def _floor(rr):
        lv = rr["levels"]["heat_cv_0.00"]
        return 100 * sum(lv[w]["p_soc_floor_ok"] * W[w] for w in W) / 151
    if ra:
        rel["econ_lam0"] = _floor(ra)
    if rz:
        rel["eps_0.00"] = _floor(rz)

    # Column names describe the dominant structural feature of the SOLVED
    # first stage (advisor rule): designs emerge from the same stochastic
    # MILP under successively tighter caps and are labelled by what the
    # optimizer changed, not by an imposed configuration.
    heads, det = [], set()
    for r in sel:
        lb = r["label"]
        if lb == "econ_lam0":
            heads.append(r"\makecell{\textbf{Economic}\\\textbf{baseline}}")
        elif lb == "det_meanT":
            heads.append(r"\makecell{\textbf{Mean-temp.}\\\textbf{benchmark}}")
            det.add(lb)
        elif r.get("eps") is not None and r["eps"] < 1e-6:
            heads.append(r"\makecell{\textbf{Full heating}\\\textbf{electrification}}")
        elif r.get("eps") is not None and r["eps"] > 7:
            heads.append(r"\makecell{\textbf{Depot-enabled}\\\textbf{abatement}}")
        else:
            heads.append(r"\makecell{\textbf{Mixed-fleet}\\\textbf{transition}}")

    def col(r, key, scale, dec, skip_det=False):
        if skip_det and r["label"] in det:
            return "---"
        return num(r[key] / scale, dec)

    rows = []
    for nm, pred in (
            ("Std.\\ battery, FFH-equipped (buses)",
             lambda b: b.ffh and b.batt_nom < 600),
            ("Std.\\ battery, electric-only",
             lambda b: not b.ffh and b.batt_nom < 600),
            ("Ext.\\ battery, FFH-equipped",
             lambda b: b.ffh and b.batt_nom > 600),
            ("Ext.\\ battery, electric-only",
             lambda b: not b.ffh and b.batt_nom > 600)):
        rows.append(f"{nm:<40} & " +
                    " & ".join(num(cnt(r, pred)) for r in sel) + r" \\")
    for nm, dep in (("Depot chargers (count$\\times$kW)", True),
                    ("Opportunity chargers", False)):
        rows.append(f"{nm:<40} & " +
                    " & ".join(fleet_of(r, dep) for r in sel) + r" \\")
    rows.append("Depot grid upgrade (kW)".ljust(40) + " & " +
                " & ".join(num(r.get("grid_kW", {}).get("depot", 0))
                           for r in sel) + r" \\")
    rows.append("Annual diesel (L)".ljust(40) + " & " +
                " & ".join(col(r, "diesel_L", 1, 0, skip_det=True)
                           for r in sel) + r" \\")
    def _cap(r):
        if r["label"] in det or r.get("eps") is None:
            return "---"
        return num(r["eps"], 2)
    rows.append("Imposed cap $\\varepsilon^{\\mathrm{ann}}$ (t\\COtwo{}/yr)"
                .ljust(40) + " & " + " & ".join(_cap(r) for r in sel) + r" \\")
    rows.append("Achieved emissions (t\\COtwo{}/yr)".ljust(40) + " & " +
                " & ".join(col(r, "co2_t", 1, 2, skip_det=True)
                           for r in sel) + r" \\")
    rows.append("Annual cost, tabulated design (kCAD/yr)".ljust(40) + " & " +
                " & ".join(num(r["F1"] / 1e3, 1) for r in sel) + r" \\")
    base_f1 = runs["econ_lam0"]["F1"]
    rows.append("Increment, tabulated design (kCAD/yr)".ljust(40) + " & " +
                " & ".join(num((r["F1"] - base_f1) / 1e3, 1) for r in sel)
                + r" \\")
    # phase-1 cost-minimizing incumbent, so the certified minimum increment
    # and the tabulated (phase-2) increment are both explicit
    def _ph1(r):
        if r["label"] in det:
            return "---"
        if r.get("phase2"):
            return num((r["phase2"]["cost_incumbent_ph1"] - base_f1) / 1e3, 1)
        return num((r["F1"] - base_f1) / 1e3, 1)
    rows.append("Increment, phase-1 incumbent (kCAD/yr)".ljust(40) + " & " +
                " & ".join(_ph1(r) for r in sel) + r" \\")
    rows.append("Feasible on full scenario set".ljust(40) + " & " +
                " & ".join("no" if r["label"] in det else "yes"
                           for r in sel) + r" \\")
    rows.append("Winter days above SoC floor (\\%)".ljust(40) + " & " +
                " & ".join(num(rel.get(r["label"]), 2) for r in sel) + r" \\")
    rows.append("Absolute optimality gap (kCAD/yr)".ljust(40) + " & " +
                " & ".join(num(r["abs_gap"] / 1e3, 2) for r in sel) + r" \\")
    # visual separator (extra space) before the mean-temperature benchmark
    # column: it is not on the stochastic emissions-reduction pathway
    ncol = len(sel)
    if det:
        colspec = "r" * (ncol - 1) + r"@{\hskip 14pt}r"
    else:
        colspec = "r" * ncol
    body = r"""\begin{table*}[!t]
\caption{Representative Route~52 designs and outcomes
(mean-temperature benchmark set apart; ``---'' marks quantities not
comparable or not evaluated for a column).}
\label{tab:designs}
\centering
\footnotesize
\setlength{\tabcolsep}{5.5pt}
\renewcommand{\arraystretch}{1.12}
\begin{tabular}{@{}l%s@{}}
\toprule
\textbf{Design or outcome} & %s \\
\midrule
%s
\bottomrule
\end{tabular}
\end{table*}
""" % (colspec, " & ".join(heads), "\n".join(rows))
    write("tab_designs.tex", body)


# ------------------------------------------------------------ division A-D
# Short two-line headers: the full case descriptions overflowed the text
# block by 73 pt. The prose defines each case, so the table only needs a key.
DIV_SHORT = {"A_fragmented": "A fragmented",
             "B_shared_infra_route_locked": "B route-locked",
             "C_shared_infra_frozen_z": "C fixed assign.",
             "D_full_coordination": "D coordinated"}
DIV_ORDER = [("A_fragmented", r"\textbf{A}"),
             ("B_shared_infra_route_locked", r"\textbf{B}"),
             ("C_shared_infra_frozen_z", r"\textbf{C}"),
             ("D_full_coordination", r"\textbf{D}")]


def table_division(div, order=None, name="tab_division.tex", caption=None,
                   label="tab:garage"):
    cases = (div or {}).get("cases", {})
    sel = [(lbl, cases[k]) for k, lbl in (order or DIV_ORDER) if k in cases]
    if not sel:
        print("SKIP tab_division: no division cases yet")
        return
    # certified bound per case: the fragmented case is a sum of independent
    # route optima, so its bound is the sum of per-route lower bounds
    def bound_of(rec):
        if "per_route" in rec:
            return sum(v["lb_solver"] for v in rec["per_route"].values())
        return rec.get("lb_solver")
    fields = [
        ("Total cost (MCAD/yr)", "total_annual_cost", 1e6, 2),
        ("Best incumbent, diff.\\ cost (kCAD/yr)", "differentiating_cost",
         1e3, 0),
        ("FFH buses", "n_ffh", 1, 0),
        ("Ext.-battery buses", "n_ext", 1, 0),
        ("Buses", "n_buses", 1, 0),
        ("Opp.\\ chargers", "n_opp_chargers", 1, 0),
        ("Diesel (kL/yr)", "diesel_L", 1e3, 1),
        ("\\COtwo{} (t/yr)", "co2_t", 1, 1),
        ("Peak depot (MW)", "peak_depot_kW", 1e3, 1),
        ("Abs.\\ gap (kCAD)", "abs_gap", 1e3, 0),
        ("Runtime (ks)", "time_s", 1e3, 1),
    ]
    rows = []
    for nm, key, scale, dec in fields:
        vals = []
        for _, rec in sel:
            v = rec.get(key)
            if key == "abs_gap" and v is None:
                v = rec.get("worst_route_gap")
            vals.append(None if v is None else v / scale)
        rows.append(f"{nm:<40} & " + " & ".join(num(v, dec) for v in vals)
                    + r" \\")
    ffh_share = []
    for _, rec in sel:
        nb, nf = rec.get("n_buses"), rec.get("n_ffh")
        ffh_share.append(None if not nb else 100.0 * nf / nb)
    rows.insert(4, "FFH share (\\%)".ljust(40) + " & "
                + " & ".join(num(v, 0) for v in ffh_share) + r" \\")
    # certified bound row, directly under the incumbent row
    rows.insert(2, "Best bound, diff.\\ cost (kCAD/yr)".ljust(40) + " & "
                + " & ".join(num(bound_of(rec) / 1e3, 0) for _, rec in sel)
                + r" \\")
    # certified saving: fragmented bound minus coordinated incumbent
    frag = cases.get("A_fragmented")
    coord = cases.get("D_full_coordination")
    if frag and coord and "per_route" in frag:
        sav = (bound_of(frag) - coord["differentiating_cost"]) / 1e3
        def _sav_cell(rec):
            if rec is coord:
                return r"$\ge$" + num(sav, 1)
            return "ref." if rec is frag else "---"
        rows.insert(3, ("Certified coordination saving (kCAD/yr)".ljust(40)
                        + " & " + " & ".join(_sav_cell(rec)
                                             for _, rec in sel) + r" \\"))
    body = r"""\begin{table}[!t]
\caption{%s}
\label{%s}
\centering
\footnotesize
\setlength{\tabcolsep}{8pt}
\renewcommand{\arraystretch}{1.12}
\begin{tabular}{@{}l%s@{}}
\toprule
\textbf{Quantity} & %s \\
\midrule
%s
\bottomrule
\end{tabular}
\end{table}
""" % (caption or "Division coordination cases.", label,
       "r" * len(sel),
       " & ".join(r"\makecell{%s}" % lbl for lbl, _ in sel),
       "\n".join(rows))
    write(name, body)


def table_stability(div):
    """Near-optimal equipment spread, taken from the case solutions themselves.

    Cases B and C add constraints to D, so their solutions are feasible for
    the coordinated problem. Together with D's own search they give several
    distinct designs within a narrow cost band -- which is precisely the
    evidence the protocol asks for, without needing an extra optimization.
    (A dedicated min/max and a solution-pool search were both attempted and
    neither produced a usable bound at this instance size.)
    """
    cases = (div or {}).get("cases", {})
    pts = []
    for k, lbl in (("C_shared_infra_frozen_z", "shared pool, fixed assignment"),
                   ("D_full_coordination", "full coordination"),
                   ("B_shared_infra_route_locked", "route-locked fleets")):
        r = cases.get(k)
        if not r:
            continue
        # where an incumbent was substituted from a nested case, the design's
        # OWN search result is kept separately and is the honest entry here
        own = r.get("own_search")
        if own:
            pts.append((lbl, own["differentiating_cost"], own["n_ffh"],
                        own["n_ext"], own["n_opp_chargers"]))
        else:
            pts.append((lbl, r["differentiating_cost"], r["n_ffh"],
                        r["n_ext"], r["n_opp_chargers"]))
    if len(pts) < 2:
        print("SKIP tab_stability: need at least two case solutions")
        return
    best = min(p[1] for p in pts)
    pts.sort(key=lambda p: p[1])
    rows = "\n".join(
        f"{lbl:<34} & {(c - best)/1e3:>5.1f} & {f:>3d} & {e:>3d} & {o:>3d} \\\\"
        for lbl, c, f, e, o in pts)
    span = (max(p[1] for p in pts) - best) / 1e3
    fmin, fmax = min(p[2] for p in pts), max(p[2] for p in pts)
    body = r"""\begin{table}[!t]
\caption{Near-optimal coordinated designs within %.1f~kCAD/yr of the best found.}
\label{tab:stability}
\centering
\footnotesize
\setlength{\tabcolsep}{5pt}
\begin{tabular}{@{}lrrrr@{}}
\toprule
\textbf{Design} & \textbf{\makecell{$\Delta$cost\\(kCAD/yr)}} &
\textbf{FFH} & \textbf{Ext.} & \textbf{Opp.} \\
\midrule
%s
\bottomrule
\end{tabular}
\end{table}
""" % (span, rows)
    write("tab_stability.tex", body)


# ---------------------------------------------------- computational report
def table_comp(runs, prov, div):
    hw = (prov or {}).get("hardware", {})
    sv = (prov or {}).get("solver", {})
    sel = [l for l in ("econ_lam0", "policy_lam100", "eps_0.00",
                       "det_meanT") if l in runs]
    rows = []
    for l in sel:
        r = runs[l]
        rows.append(f"R52 {l.replace(chr(95), chr(92) + chr(95))[:14]} & "
                    f"{num(r['obj'] / 1e3, 1)} & {num(r['lb'] / 1e3, 1)} & "
                    f"{num(r['abs_gap'])} & {r['rel_gap'] * 100:.3f} & "
                    f"{num(r['time_s'])} & {r['status']} \\\\")
    for k, lbl in DIV_ORDER:
        rec = (div or {}).get("cases", {}).get(k)
        if not rec:
            continue
        g = rec.get("abs_gap", rec.get("worst_route_gap"))
        rows.append(
            f"Div {DIV_SHORT.get(k, k)[:8]} & "
            f"{num(rec.get('differentiating_cost', 0) / 1e3, 1)} & --- & "
            f"{num(g)} & --- & {num(rec.get('time_s'))} & "
            f"{rec.get('status', '---')} \\\\")
    body = r"""\begin{table*}[!t]
\caption{Computational performance on %s (%s cores, %s GB); solver %s %s, %s threads.}
\label{tab:comp}
\centering
\scriptsize
\setlength{\tabcolsep}{4pt}
\begin{tabular}{@{}lrrrrrr@{}}
\toprule
\textbf{Instance} & \textbf{Incumbent} & \textbf{Bound} &
\textbf{Abs.\ gap} & \textbf{Rel.\ gap (\%%)} & \textbf{Runtime (s)} &
\textbf{Status} \\
\midrule
%s
\bottomrule
\end{tabular}
\end{table*}
""" % (hw.get("machine", "---"), hw.get("cores", "---"),
       hw.get("ram_gb", "---"), sv.get("name", "Gurobi"),
       ".".join(str(v) for v in sv.get("version", [])) or "---",
       sv.get("threads", "---"), "\n".join(rows))
    write("tab_comp.tex", body)


if __name__ == "__main__":
    d = load(RES)
    runs = {r["label"]: r for r in d["runs"]
            if "error" not in r and not r.get("infeasible")} if d else {}
    div = load(DIV)
    prov = load(PROV)
    print(f"{len(runs)} Route 52 runs | "
          f"{len((div or {}).get('cases', {}))} division cases")
    table_scen(runs)
    table_designs(runs)
    table_division(
        div, order=[("A_fragmented", r"\textbf{Fragmented}"),
                    ("D_full_coordination", r"\textbf{Coordinated}")],
        name="tab_division.tex", label="tab:garage",
        caption="Fragmented versus fully coordinated planning for the "
                "Arrow Road division.")
    table_division(
        div, name="tab_division_full.tex", label="tab:garage-full",
        caption="All division coordination cases: A fragmented, B "
                "route-locked, C fixed assignment, D full coordination.")
    table_stability(div)
    table_comp(runs, prov, div)
    print("\nInclude in main.tex with e.g. \\input{tables_v6/tab_designs}")
