"""
Route 52 prototype v6 — two-stage stochastic MILP for winter-resilient BEB
planning and operation (Paper 2, revision-protocol formulation).

v6 changes (audit of the v5 formulation, REVISION_AUDIT.md Section 3):
  C1  depot preconditioning power is bounded by the ELECTRIC HEATER rating,
      not only by charging acceptance and charger rating. The v5 model let
      up to 40 kW pass through a 23 kW heater in one 0.25 h step; the bound
      was active at the v5 optimum (test_ppre_rating.py), so every v5 run
      was re-solved.
  C2  preconditioning heat credit carries a thermal-retention coefficient
      chi_{b,t} = exp(-(t_dep - t)/tau), tau = PRECOND_TAU_H (0.5 h default,
      swept for sensitivity). Delivered plug energy and credited cabin heat
      are now separate quantities; chi <= 1 makes the credit conservative
      relative to v5, which credited preconditioning at chi = 1.
  C3  one plug per bus per step across ALL sites, charging and
      preconditioning combined (was structurally true, now structural).
  C4  ffh_free flag: FFH-free PROCUREMENT (x_kappa = 0 for FFH classes), as
      distinct from the zero-emissions cap, which only forbids FFH operation.
  C5  preconditioning diagnostics exposed for the run records.

v5 changes (T-ITS revision protocol):
  R1  heater rated-output limits: q_el <= dur * 23 kW (telemetry p99),
      q_ffh <= dur * 12 kW * z_ffh (Paper 1 winter-conditions output)
  R2  off-season scenario (214 days @ ECCC Apr-Oct mean, zero cabin heat):
      scenario weights sum to 365; objective is a true annual cost
  R3  billing-period demand charges: winter peak x 5 months + off-season
      peak x 7 months (conservative representative-day in each period)
  R4  explicit charging/preconditioning plug-exclusivity guard u + upre <= 1
      (windows are disjoint by construction; guard makes it structural)
  R5  optional spare ratio, fixed fleet total, and differentiating-cost
      objective (division-scale certification)
  R6  emissions expression exposed for lexicographic eps-constraint phase 2

v3 = v2 model (all audit fixes) + REAL DATA via route52_inputs.json
(generated by fit_inputs.py from the heating_system_study repo + ECCC):
  - traction interface fitted on 13,757 TTC telemetry runs (drivetrain only)
  - Route 52 blocks built from GTFS-derived branch data (52A/52D/52G,
    Lawrence Stn <-> Pearson / Victory-McNaughton / Martin Grove), 18 blocks
  - 5 temperature bands with ECCC Toronto City day counts (2 winters)
  - grid tiers at 200 $/kW (NREL/industry range); FFH O&M 1,000 $/yr (assumption)

Audit fixes retained from v2: #1 overnight cyclic closure, #2 arrival-SoC
reserve, #3 explicit priced preconditioning, #4 monthly billing peaks,
#5 single annual weights, #6 carbon $/t conversion, #9 one charger class per
site, #10 class-dependent traction, #11 bounded phi, #12 nominal-capacity
convention, #17 asset CRFs + tiered grid upgrades.

Usage:  python3 route52_prototype.py [--sweep N]
"""

import argparse
import json
import math
import os
from dataclasses import dataclass, field

import gurobipy as gp
from gurobipy import GRB

# ----------------------------------------------------------------------------
# 1. Data (real inputs from route52_inputs.json)
# ----------------------------------------------------------------------------

_HERE = os.path.dirname(os.path.abspath(__file__))
_INPUT_FILE = os.environ.get("ROUTE_INPUTS", "route52_inputs.json")
with open(os.path.join(_HERE, _INPUT_FILE)) as f:
    INP = json.load(f)

DT = 0.25
T0 = INP["service_start_h"]           # 05:00
T_SVC_END = INP["service_end_h"]      # 22:00
T_END = 29.0                          # overnight until 05:00 next day
STEPS = range(int((T_END - T0) / DT))
def step_hour(t):
    h = T0 + (t + 0.5) * DT
    return h if h < 24 else h - 24

@dataclass
class BusClass:
    name: str
    batt_nom: float
    ffh: bool
    cost: float
    mass_pen: float

BATT_COST = 150.0
BUS_BASE = 1_000_000.0
MASS_PEN_EXT = 0.02
BUS_CLASSES = [
    BusClass("NF-std-FFH",   525.0, True,  BUS_BASE, 0.0),
    BusClass("NF-std-eOnly", 525.0, False, BUS_BASE, 0.0),
    BusClass("NF-ext-FFH",   643.0, True,  BUS_BASE + 118 * BATT_COST, MASS_PEN_EXT),
    BusClass("NF-ext-eOnly", 643.0, False, BUS_BASE + 118 * BATT_COST, MASS_PEN_EXT),
]
S_UP, S_LO = 0.85, 0.10
RESERVE_RETURN = 10.0
FFH_ANNUAL_OM = INP["ffh_annual_om"]          # 1,000 $/yr (assumption, doc'd)
BUS_ACCEPT = 450.0
ETA_CH, ETA_EL = 0.95, 1.0
CRF_BUS, CRF_CH, CRF_GRID = 0.1128, 0.0963, 0.0802

SITES = INP.get("sites", ["depot", "lawrenceStn", "pearson",
                          "victoryMcNaughton", "lawrenceWestStn", "martinGrove"])
GRID_EXISTING = {n: (600.0 if n == "depot" else 0.0) for n in SITES}
GRID_TIERS = INP.get("grid_tiers", [250.0, 500.0, 1000.0])
GRID_COST_PER_KW = INP["grid_upgrade_cost_per_kw"]     # 200 $/kW (NREL range)
GRID_TIER_COST = [GRID_COST_PER_KW * g for g in GRID_TIERS]
CH_CLASSES = [100, 150, 200, 300, 450]
SITE_FIXED_COST = 150_000.0   # $ per newly activated terminal charging site
                              # (civil works, switchgear, interconnection) TODO source
def max_ch(n):                # depot must refill whole fleet overnight
    return 64 if n == "depot" else 8
def charger_cost(p):
    pts = [(50, 40_000), (90, 66_000), (160, 160_000), (440, 334_000)]
    if p <= pts[0][0]: return pts[0][1]
    for (p1, c1), (p2, c2) in zip(pts, pts[1:]):
        if p <= p2:
            return c1 + (c2 - c1) * (p - p1) / (p2 - p1)
    return pts[-1][1] * p / pts[-1][0]

def tou(t):
    h = step_hour(t)
    if 7 <= h < 11 or 17 <= h < 19: return 0.182
    if 11 <= h < 17:                return 0.122
    return 0.087
DEMAND_CHARGE_MONTH = 12.0
WINTER_MONTHS = 5
OFFSEASON_MONTHS = 7
DIESEL_PRICE = 1.86
CO2_PER_L = 2.68
DIESEL_LHV = 9.96
CARBON_PRICE_T = 100.0

# scenarios: ECCC Toronto City, winters 2024-25 & 2025-26 (see fit_inputs.py)
# + off-season (Apr-Oct, zero cabin heat) when present in the input file (v5)
SCEN = {name: (s["T"], s["days"]) for name, s in INP["scenarios"].items()}
HEATLESS = {name for name, s in INP["scenarios"].items()
            if not s.get("heat", True)}

# heater rated outputs (v5 R1): FFH 12 kW winter-conditions useful output
# (Paper 1); electric heater 23 kW = p99 of eHeat-energy/heating-time over
# 9,001 telemetry runs. Fallbacks keep pre-v5 inputs runnable.
P_FFH_RATED = INP.get("ffh_rated_kw", 12.0)
P_ELH_RATED = INP.get("el_heater_rated_kw", 23.0)

# cold-weather derating (reviewer fix: usable capacity + charging acceptance
# vary with ambient T; defaults conservative for thermally managed packs,
# override via INP["derates"])  TODO fleet-specific validation
def _derates(T):
    cap = 1.0 - max(0.0, -T) * 0.004      # -20C -> 0.92
    acc = 1.0 - max(0.0, -T) * 0.008      # -20C -> 0.84
    return max(cap, 0.85), max(acc, 0.75)
DERATE = {w: INP.get("derates", {}).get(w) or _derates(SCEN[w][0])
          for w in SCEN}

# --- thermal demand: Paper 1 Table 4 posterior medians (New Flyer) ----------
B0, B1, B2 = 4.5130, 0.1839, 0.0009
B3, B4, B5 = 0.1889, -0.4642, -0.2023
E_DOOR, E_PAX = 0.0014, 0.027
CABIN_T, R_DRV = 20.0, 0.85
F_PAX, RHO_SOLAR_W = INP["pax_per_h"], 0.15

def q_heat_rate(T_amb, f_stop, v):
    dT = CABIN_T - T_amb
    return max(0.0, B0 + B1 * dT + B2 * v * R_DRV * dT
               + B3 * f_stop * dT * E_DOOR + B4 * F_PAX * E_PAX
               + B5 * RHO_SOLAR_W)

def phi_useful(T_amb):
    return min(1.0, max(0.05, 0.5192 + 0.0054 * T_amb))

# --- traction: fitted interface (Choga-style), drivetrain only --------------
_TR = INP["traction"]
def e_traction_per_km(T_amb, v):
    return (_TR["a0"] + _TR["a1_cold"] * max(0.0, _TR["T_ref"] - T_amb)
            + _TR["a2_speed"] * v)

# --- Route 52 blocks from GTFS-derived branch data --------------------------
DEADHEAD_KM = INP["deadhead_km"]
PRECOND_MAX_KWH = 10.0

# C2: thermal-retention time constant for preconditioning credit. Cabin
# temperature between pull-out and the first trip is not telemetered, so this
# is a documented conservative assumption, not an estimate: heat delivered
# tau hours before departure is credited at exp(-1). Swept in the campaign.
PRECOND_TAU_H = 0.5

def precond_chi(blk, t):
    """Retained fraction of preconditioning heat delivered in step t."""
    gap = max(0.0, blk.pullout_h - (T0 + (t + 0.5) * DT))
    return math.exp(-gap / PRECOND_TAU_H)

@dataclass
class Trip:
    dist_km: float
    dur_h: float
    speed: float
    f_stop: float          # stops per hour (door-loss driver)

@dataclass
class Block:
    bid: int
    branch: str
    trips: list = field(default_factory=list)      # Trip
    dwells: list = field(default_factory=list)     # (site, s, e) after trip i
    pullout_h: float = 0.0
    pullin_h: float = 0.0

def build_blocks():
    blocks, bid = [], 0
    for bname, br in INP["branches"].items():
        e, w = br["east"], br["west"]
        legs = {
            "west": Trip(w["dist_km"], w["dur_min"] / 60, w["speed_kmh"],
                         w["stops"] / (w["dur_min"] / 60)),
            "east": Trip(e["dist_km"], e["dur_min"] / 60, e["speed_kmh"],
                         e["stops"] / (e["dur_min"] / 60)),
        }
        lay = {"west": w["layover_min"] / 60, "east": e["layover_min"] / 60}
        site = {"west": br["site_west"], "east": br["site_east"]}
        headway_h = min(e["headway_min"], w["headway_min"]) / 60
        # service windows: all-day default; express branches get peak-only
        windows = br.get("windows", [[T0 + 0.25, T_SVC_END - 0.25]])
        for k in range(br["n_buses"]):
            blk = Block(bid, bname)
            blk.pullout_h = windows[0][0] + k * headway_h
            t = blk.pullout_h
            leg = "west"                       # start at east terminus, go west
            for wi, (ws, we) in enumerate(windows):
                t = max(t, ws)
                while True:
                    tr = legs[leg]
                    if t + tr.dur_h > we:
                        break
                    blk.trips.append(tr)
                    t += tr.dur_h
                    arr_side = leg             # arrive at 'leg' side terminus
                    nxt = legs["east" if leg == "west" else "west"]
                    if t + lay[arr_side] + nxt.dur_h <= we and lay[arr_side] > 1e-6:
                        blk.dwells.append((site[arr_side], t, t + lay[arr_side]))
                        t += lay[arr_side]
                    elif len(blk.trips) > 0:
                        blk.dwells.append((site[arr_side], t, t))   # zero-length
                    leg = "east" if leg == "west" else "west"
                # between windows: midday depot layover (chargeable)
                if wi < len(windows) - 1 and blk.trips:
                    nxt_start = windows[wi + 1][0] + k * headway_h
                    dd = INP["deadhead_min"] / 60
                    if nxt_start - dd > t + dd:
                        blk.dwells.append(("depot", t + dd, nxt_start - dd))
                    t = nxt_start
            # trim trailing dwells with no following trip
            while len(blk.dwells) >= len(blk.trips) and blk.dwells:
                blk.dwells.pop()
            blk.pullin_h = t + INP["deadhead_min"] / 60
            if blk.trips:
                blocks.append(blk); bid += 1
    return blocks

BLOCKS = build_blocks()
N_BLOCKS = len(BLOCKS)

def _overlap_frac(s, e, t):
    a, bnd = T0 + t * DT, T0 + (t + 1) * DT
    return max(0.0, min(e, bnd) - max(s, a)) / DT

def avail_frac(blk):
    out = {}
    for (site, s, e) in blk.dwells:
        if site not in SITES:          # non-candidate terminus: dwell, no charging
            continue
        for t in STEPS:
            f = _overlap_frac(s, e, t)
            if f > 1e-6:
                out[(site, t)] = out.get((site, t), 0.0) + f
    for t in STEPS:
        f = _overlap_frac(blk.pullin_h, T_END, t)
        if f > 1e-6:
            out[("depot", t)] = out.get(("depot", t), 0.0) + f
    return out

def precond_steps(blk):
    return [t for t in STEPS if blk.pullout_h - 1.0 <= T0 + t * DT < blk.pullout_h]

AVAIL = {blk.bid: avail_frac(blk) for blk in BLOCKS}
PRE_STEPS = {blk.bid: precond_steps(blk) for blk in BLOCKS}

# ----------------------------------------------------------------------------
# 2. Model  (Section III draft v2; audit fixes as tagged in v2 header)
# ----------------------------------------------------------------------------

SHORTFALL_PENALTY = 1000.0     # $/kWh on elastic energy slack (simulation only)


def build_model(eps_cap_t=None, carbon_price_t=CARBON_PRICE_T, eta_el_by_scen=None,
                spare_ratio=0.0, fix_fleet_total=False, diff_objective=False,
                load_mult=None, elastic=False, only_scen=None, ffh_free=False):
    """...
    v5 simulation hooks (defaults reproduce the planning model exactly):
      load_mult  {(w, b, i): (traction_mult, heat_mult)} multiplicative
                 realization of residual energy-demand uncertainty
      elastic    add penalized shortfall slack to the arrival-reserve, SoC
                 floor, and overnight-closure constraints so an infeasible
                 realization is measured instead of rejected
      only_scen  build a single weather scenario (out-of-sample simulation)
    """
    """v5 model. spare_ratio: sum_b z <= (1-psi) x per class (psi > 0 forces
    spares). fix_fleet_total: sum_k x = N_BLOCKS (valid when spare_ratio=0;
    every optimum satisfies it since base bus cost > 0). diff_objective:
    charge bus capital as (c_kappa - BUS_BASE) so the solver optimizes
    differentiating cost only; requires fix_fleet_total, and reporting adds
    CRF_BUS*BUS_BASE*N_BLOCKS back."""
    assert not (diff_objective and not fix_fleet_total), \
        "diff_objective requires fix_fleet_total"
    assert not (fix_fleet_total and spare_ratio > 0), \
        "fixed fleet total incompatible with spare ratio"
    m = gp.Model("route52_two_stage_v5")
    K, B = range(len(BUS_CLASSES)), [b.bid for b in BLOCKS]
    N, P = SITES, CH_CLASSES
    W = [only_scen] if only_scen else list(SCEN.keys())
    J = range(len(GRID_TIERS))
    HW = {w: SCEN[w][1] for w in W}
    LM = load_mult or {}
    slack_terms = []

    x = m.addVars(K, vtype=GRB.INTEGER, ub=N_BLOCKS + 20, name="x_bus")
    if fix_fleet_total:
        m.addConstr(x.sum() == N_BLOCKS, name="fleet_total")
    if ffh_free:                      # C4: FFH-free procurement, not just
        for k in K:                   # FFH-free operation
            if BUS_CLASSES[k].ffh:
                m.addConstr(x[k] == 0, name=f"ffh_free_{k}")
    wch = m.addVars(N, P, vtype=GRB.INTEGER,
                    ub={(n, p): max_ch(n) for n in N for p in P}, name="w_ch")
    ysite = m.addVars(N, P, vtype=GRB.BINARY, name="y_site")
    ygrid = m.addVars(N, J, vtype=GRB.BINARY, name="y_grid")
    for n in N:
        m.addConstr(gp.quicksum(ysite[n, p] for p in P) <= 1)
        m.addConstr(gp.quicksum(ygrid[n, j] for j in J) <= 1)
        for p in P:
            m.addConstr(wch[n, p] <= max_ch(n) * ysite[n, p])
    g_add = {n: gp.quicksum(GRID_TIERS[j] * ygrid[n, j] for j in J) for n in N}

    bus_cost = {k: (BUS_CLASSES[k].cost - (BUS_BASE if diff_objective else 0.0))
                for k in K}
    capex = (CRF_BUS * gp.quicksum(bus_cost[k] * x[k] for k in K)
             + CRF_CH * gp.quicksum(charger_cost(p) * wch[n, p] for n in N for p in P)
             + CRF_CH * SITE_FIXED_COST * gp.quicksum(
                   ysite[n, p] for n in N for p in P if n != "depot")
             + CRF_GRID * gp.quicksum(GRID_TIER_COST[j] * ygrid[n, j] for n in N for j in J)
             + FFH_ANNUAL_OM * gp.quicksum(x[k] for k in K if BUS_CLASSES[k].ffh))

    # v5 R3: separate winter / off-season billing peaks (conservative
    # representative-day within each period)
    PERIODS = ["win", "off"]
    N_MONTHS = {"win": WINTER_MONTHS, "off": OFFSEASON_MONTHS}
    rho = m.addVars(N, PERIODS, lb=0.0, name="rho_period")
    demand_annual = DEMAND_CHARGE_MONTH * gp.quicksum(
        N_MONTHS[l] * rho[n, l] for n in N for l in PERIODS)

    opex, diesel = {}, {}
    m._scen = {}
    for w in W:
        T_amb = SCEN[w][0]
        phi = phi_useful(T_amb)
        eta_el_w = (eta_el_by_scen or {}).get(w, ETA_EL)
        cap_der, acc_der = DERATE[w]
        acc_w = BUS_ACCEPT * acc_der

        TI = [(b, i) for b in B for i in range(len(BLOCKS[b].trips))]
        ckeys = [(b, n, t) for b in B for (n, t) in AVAIL[b]]
        pkeys = [(b, t) for b in B for t in PRE_STEPS[b]]

        z = m.addVars(B, K, vtype=GRB.BINARY, name=f"z_{w}")
        u = m.addVars(ckeys, vtype=GRB.BINARY, name=f"u_{w}")
        c = m.addVars(ckeys, lb=0.0, name=f"c_{w}")
        ppre = m.addVars(pkeys, lb=0.0, name=f"ppre_{w}")
        upre = m.addVars(pkeys, vtype=GRB.BINARY, name=f"upre_{w}")
        qel = m.addVars(TI, lb=0.0, name=f"qel_{w}")
        qff = m.addVars(TI, lb=0.0, name=f"qff_{w}")
        # Under `elastic` (out-of-sample simulation) the state-of-charge
        # variables must be free below zero. With lb=0 a realization whose
        # demand exceeds the pack returns INFEASIBLE rather than a measured
        # shortfall: the penalized slack relaxes the reserve, the SoC floor
        # and overnight closure, but nothing relaxes non-negativity. That
        # dropped the worst days out of the shortfall statistic entirely and
        # biased it low exactly where it matters. Planning solves keep lb=0.
        _elb = -GRB.INFINITY if elastic else 0.0
        Edep = m.addVars(TI, lb=_elb, name=f"Edep_{w}")
        Earr = m.addVars(TI, lb=_elb, name=f"Earr_{w}")
        D = m.addVar(lb=0.0, name=f"D_{w}")

        for b in B:
            blk, av = BLOCKS[b], AVAIL[b]
            nt = len(blk.trips)
            m.addConstr(z.sum(b, "*") == 1)
            cap = cap_der * gp.quicksum(BUS_CLASSES[k].batt_nom * z[b, k] for k in K)

            # trip loads (class-dependent traction; deadhead on first/last trip)
            # v5 R2: heatless scenarios (off-season) carry zero cabin heat
            qtrip, e_use = {}, {}
            for i, tr in enumerate(blk.trips):
                tm, hm = LM.get((w, b, i), (1.0, 1.0))
                qtrip[i] = (0.0 if w in HEATLESS
                            else hm * q_heat_rate(T_amb, tr.f_stop, tr.speed)
                            * tr.dur_h)
                dist = tr.dist_km + (DEADHEAD_KM if i in (0, nt - 1) else 0.0)
                ekm = tm * e_traction_per_km(T_amb, tr.speed)
                e_use[i] = gp.quicksum(ekm * dist * (1 + BUS_CLASSES[k].mass_pen)
                                       * z[b, k] for k in K)

            # preconditioning (fix #3; through EVSE: plug + rating + acceptance)
            # qpre_e  = cabin heat delivered at the plug over the window
            # qpre_cr = share of it still retained at departure (C2)
            qpre_e = eta_el_w * DT * gp.quicksum(ppre[b, t] for t in PRE_STEPS[b])
            qpre_cr = eta_el_w * DT * gp.quicksum(
                precond_chi(blk, t) * ppre[b, t] for t in PRE_STEPS[b])
            m.addConstr(qpre_e <= PRECOND_MAX_KWH)
            m.addConstr(qpre_cr <= qtrip[0])
            for t in PRE_STEPS[b]:
                m.addConstr(ppre[b, t] <= acc_w * upre[b, t])
                m.addConstr(ppre[b, t] <=
                            gp.quicksum(p * ysite["depot", p] for p in P))
                # C1: preconditioning heat passes through the same electric
                # cabin heater as in-service electric heat, so it is bounded
                # by the heater's rated output, not by charging acceptance
                m.addConstr(ppre[b, t] <= P_ELH_RATED)
                # v5 R4 / C3: one EVSE connection per bus and step, charging
                # and preconditioning combined, across every site
                sites_t = [n for n in N if (b, n, t) in u]
                if sites_t:
                    m.addConstr(gp.quicksum(u[b, n, t] for n in sites_t)
                                + upre[b, t] <= 1)

            # C3: one plug per bus per step also outside the precond window
            for t in STEPS:
                sites_t = [n for n in N if (b, n, t) in u]
                if len(sites_t) > 1:
                    m.addConstr(gp.quicksum(u[b, n, t] for n in sites_t) <= 1)

            for i in range(nt):
                credit = qpre_cr if i == 0 else 0.0
                m.addConstr(qel[b, i] + qff[b, i] + credit == qtrip[i])
                m.addConstr(qff[b, i] <= qtrip[i] *
                            gp.quicksum(z[b, k] for k in K if BUS_CLASSES[k].ffh))
                # v5 R1: rated heater outputs (energy <= duration x rating)
                dur = blk.trips[i].dur_h
                m.addConstr(qel[b, i] <= dur * P_ELH_RATED)
                m.addConstr(qff[b, i] <= dur * P_FFH_RATED *
                            gp.quicksum(z[b, k] for k in K if BUS_CLASSES[k].ffh))

            for (n, t), favail in av.items():
                m.addConstr(c[b, n, t] <= acc_w * favail * u[b, n, t])
                m.addConstr(c[b, n, t] <= favail *
                            gp.quicksum(p * ysite[n, p] for p in P))

            # SoC (fixes #1, #2, #12)
            # elastic slack (simulation only): measures energy shortfall
            # instead of returning an infeasible model
            sl = (m.addVars(range(nt), lb=0.0, name=f"slack_{w}_{b}")
                  if elastic else None)
            sl_ret = m.addVar(lb=0.0, name=f"slackret_{w}_{b}") if elastic else None
            sl_cyc = m.addVar(lb=0.0, name=f"slackcyc_{w}_{b}") if elastic else None
            if elastic:
                slack_terms += [sl[i] for i in range(nt)] + [sl_ret, sl_cyc]

            m.addConstr(Edep[b, 0] == S_UP * cap)
            for i in range(nt):
                m.addConstr(Earr[b, i] == Edep[b, i] - e_use[i] - qel[b, i] / eta_el_w)
                m.addConstr(Earr[b, i] >= S_LO * cap - (sl[i] if elastic else 0.0))
                m.addConstr(Edep[b, i] <= S_UP * cap)
                if i < nt - 1:
                    site, s_, e_ = blk.dwells[i]
                    steps_in = [t for t in STEPS if _overlap_frac(s_, e_, t) > 1e-6]
                    R = ETA_CH * DT * gp.quicksum(c[b, site, t] for t in steps_in
                                                  if (b, site, t) in c)
                    m.addConstr(Edep[b, i + 1] == Earr[b, i] + R)
            m.addConstr(Earr[b, nt - 1] >= S_LO * cap + RESERVE_RETURN
                        - (sl_ret if elastic else 0.0))
            post_steps = [t for t in STEPS if ("depot", t) in av
                          and _overlap_frac(blk.pullin_h, T_END, t) > 1e-6]
            m.addConstr(Earr[b, nt - 1]
                        + ETA_CH * DT * gp.quicksum(c[b, "depot", t] for t in post_steps)
                        + (sl_cyc if elastic else 0.0)
                        == S_UP * cap)

        for k in K:
            m.addConstr(gp.quicksum(z[b, k] for b in B)
                        <= (1.0 - spare_ratio) * x[k])

        # site coupling (fixes #1, #3, #4)
        for n in N:
            for t in STEPS:
                users = [b for b in B if (n, t) in AVAIL[b]]
                if not users and n != "depot":
                    continue
                occ = gp.quicksum(u[b, n, t] for b in users)
                site_load = gp.quicksum(c[b, n, t] for b in users)
                if n == "depot":
                    occ = occ + gp.quicksum(upre[b, t] for b in B if (b, t) in upre)
                    site_load = site_load + gp.quicksum(
                        ppre[b, t] for b in B if (b, t) in ppre)
                m.addConstr(occ <= wch.sum(n, "*"))
                m.addConstr(site_load <= gp.quicksum(p * wch[n, p] for p in P))
                m.addConstr(site_load <= GRID_EXISTING[n] + g_add[n])
                m.addConstr(rho[n, "off" if w in HEATLESS else "win"]
                            >= site_load)

        m.addConstr(D == gp.quicksum(qff[b, i] for (b, i) in TI) / (phi * DIESEL_LHV))
        diesel[w] = D

        energy_cost = (gp.quicksum(tou(t) * DT * c[b, n, t] for (b, n, t) in ckeys)
                       + gp.quicksum(tou(t) * DT * ppre[b, t] for (b, t) in pkeys))
        opex[w] = energy_cost + DIESEL_PRICE * D \
                  + carbon_price_t * CO2_PER_L * D / 1000.0
        m._scen[w] = dict(z=z, u=u, c=c, ppre=ppre, upre=upre, qel=qel, qff=qff,
                          Edep=Edep, Earr=Earr, D=D, energy_cost=energy_cost)

    emis_t = gp.quicksum(HW[w] * CO2_PER_L * diesel[w] for w in W) / 1000.0
    if eps_cap_t is not None:
        m.addConstr(emis_t <= eps_cap_t, name="eps_cap")

    total_cost = capex + demand_annual + gp.quicksum(HW[w] * opex[w] for w in W)
    shortfall = gp.quicksum(slack_terms) if slack_terms else 0.0
    m.setObjective(total_cost + SHORTFALL_PENALTY * shortfall, GRB.MINIMIZE)
    m._shortfall = shortfall
    m._handles = dict(x=x, wch=wch, ysite=ysite, ygrid=ygrid, rho=rho,
                      opex=opex, diesel=diesel, demand_annual=demand_annual,
                      g_add=g_add)
    # v5 R6: expressions for lexicographic phase 2 and reporting
    m._emis_t = emis_t
    m._total_cost = total_cost
    m._const_addback = (CRF_BUS * BUS_BASE * N_BLOCKS if diff_objective else 0.0)
    return m

# ----------------------------------------------------------------------------
# 3. Solve + report
# ----------------------------------------------------------------------------

def solve_and_report(eps_cap_t=None, label="base", quiet=False):
    m = build_model(eps_cap_t=eps_cap_t)
    m.Params.MIPGap = 0.01
    m.Params.TimeLimit = 1200
    if quiet:
        m.Params.OutputFlag = 0
    m.optimize()
    if m.SolCount == 0:
        print(f"[{label}] no solution, status {m.Status}")
        return None
    h = m._handles
    K = range(len(BUS_CLASSES))
    x, wch, rho = h["x"], h["wch"], h["rho"]
    res = {
        "label": label, "objective": round(m.ObjVal, 0), "gap": round(m.MIPGap, 4),
        "n_blocks": N_BLOCKS,
        "fleet": {BUS_CLASSES[k].name: int(round(x[k].X)) for k in K if x[k].X > 0.5},
        "chargers": {f"{n}:{p}kW": int(round(wch[n, p].X))
                     for n in SITES for p in CH_CLASSES if wch[n, p].X > 0.5},
        "grid_upgrade_kW": {n: round(h["g_add"][n].getValue(), 0)
                            for n in SITES if h["g_add"][n].getValue() > 1},
        "monthly_peak_kW": {n: round(rho[n].X, 1) for n in SITES if rho[n].X > 1},
        "annual_demand_charges": round(h["demand_annual"].getValue(), 0),
        "winter_energy_opex": round(sum(SCEN[w][1] * h["opex"][w].getValue()
                                        for w in SCEN), 0),
        "winter_diesel_L": round(sum(SCEN[w][1] * h["diesel"][w].X for w in SCEN), 0),
        "winter_CO2_t": round(sum(SCEN[w][1] * h["diesel"][w].X for w in SCEN)
                              * CO2_PER_L / 1000, 2),
        "diesel_L_per_day": {w: round(h["diesel"][w].X, 1) for w in SCEN},
    }
    print(json.dumps(res, indent=2))
    return res

if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("--sweep", type=int, default=0)
    args = ap.parse_args()
    print(f"blocks: {N_BLOCKS} "
          f"({', '.join(f'{b.branch}#{b.bid}:{len(b.trips)}trips' for b in BLOCKS[:6])} ...)")
    print("=== Route 52 prototype v3 (real data): base solve ===")
    base = solve_and_report(label="base")
    if args.sweep and base:
        cap0 = max(base["winter_CO2_t"], 0.01)
        results = [base]
        for j in range(1, args.sweep + 1):
            eps = cap0 * (1 - j / args.sweep)
            print(f"\n=== sweep {j}/{args.sweep}: cap = {eps:.2f} t CO2/yr ===")
            r = solve_and_report(eps_cap_t=eps, label=f"eps_{j}", quiet=True)
            if r: results.append(r)
        with open("route52_sweep.json", "w") as f:
            json.dump(results, f, indent=2)
        print("\nsweep saved to route52_sweep.json")
